### ISSUE TITLE
Android studio3.0空指针异常

### ISSUE THREAD

**Issue by caoyy** [Skykai521/ECTranslation#66]
环境：Android studio3.0
空指针异常。之后再敲快捷键再无反应。
错误日志：
null
java.lang.NullPointerException
	at com.intellij.ide.SystemHealthMonitor.getActionName(SystemHealthMonitor.java:640)
	at com.intellij.ide.SystemHealthMonitor.countActionInvocation(SystemHealthMonitor.java:547)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.fireBeforeActionPerformed(ActionManagerImpl.java:1183)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:612)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by OkamiyGit** [comment]
建议你下载最新的版本（我用的是1.5，as3.0.1），重启studio试试
