### ISSUE TITLE
突然间爆出来的 gson  认为这是对象不是字符串版本1.5的  

### ISSUE THREAD

**Issue by 18736190608** [Skykai521/ECTranslation#80]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at com.boohee.plugin.translation.RequestRunnable.run(RequestRunnable.java:65)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 6 more

**Comment by kbja** [comment]
你看下他的源码，他RequestRunnable的65行，明显是上面http请求返回了错误，不是200+，然后解析错误失败。猜测是有道api改了，或者到期了

**Comment by uniquezhangqi** [comment]
这个如何解决

**Comment by kbja** [comment]
> 这个如何解决

就是个get请求，你去看下他拼url的方法，然后用postman试一下就完了。最近事儿太多，要不然我就自己改了
